services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "enrichment"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${DB_VOLUME_HOST_URI}:/var/lib/postgresql/data
    networks:
      - enrichment
    ports:
      - "5432:5432"

  enrichment:
    image: dtikhonov/enrichment:latest
    restart: always
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ACTIVE_PROFILES: ${ACTIVE_PROFILES}
    networks:
      - enrichment
    ports:
      - "8081:8081"
    depends_on:
      - postgres

networks:
  enrichment:
    driver: bridge