spring:
  main:
    web-application-type: NONE
    banner-mode: OFF

mapping:
  accounts: configs/account-mapping.csv
  categories: configs/categories-mapping.csv
output-file:
  name: financePM_{date}_enriched.data
  date-pattern: dd-MM-yyyy