spring:
  application.name: enrichment
  main.banner-mode: OFF
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/enrichment
    username: enrichment
    password: enrichment
    hikari:
      connection-timeout: 5000
      leak-detection-threshold: 300000
      maximum-pool-size: 5
      pool-name: PrimaryPool
      auto-commit: true
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
    enabled: true
  batch:
    job.enabled: true
    jdbc.initialize-schema: always
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    root: INFO
    liquibase: INFO

mapping:
  accounts: configs/account-mapping.csv
  categories: configs/categories-mapping.csv
output-file:
  name: financePM_{date}_enriched.data
  date-pattern: dd-MM-yyyy