spring:
  application.name: enrichment
  main.banner-mode: OFF
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL}
    username: enrichment
    password: enrichment
    hikari:
      connection-timeout: 5000
      leak-detection-threshold: 30000
      max-lifetime: 900000
      maximum-pool-size: 5
      pool-name: PrimaryPool
      auto-commit: true
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
    enabled: true
  batch:
    job.enabled: false
    jdbc.initialize-schema: never
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    root: INFO
    liquibase: INFO
    ru.tikhonovdo.enrichment.service: TRACE

selenium-waiting-period: 30s
selenoid-host-download-path: ${SELENOID_HOST_DOWNLOAD_PATH} # make sure that all users can write to this path

server:
  port: 8081
  servlet.session:
    timeout: 5m
    cookie:
      http-only: true
      secure: false
    tracking-modes: cookie

import:
  last-transaction-default-period: P6M
  tinkoff:
    home-url: https://www.tbank.ru/mybank/
    api-url: https://www.tbank.ru/api/common/v1
  alfa:
    home-url: https://web.alfabank.ru/
    api-url: https://web.alfabank.ru/api/v1/
  yandex:
    login-url: https://passport.yandex.ru/auth?origin=user_id&retpath=https%3A%2F%2Fbank.yandex.ru%2F%3Fchange_yandex_session%3Dtrue
    url: https://bank.yandex.ru/

refund:
  income-category-id: 79

---
spring:
  config.activate.on-profile: test
import:
  last-transaction-default-period: P100Y